services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jakubferenc-wp
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./.docker/certs:/etc/apache2/ssl
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: jakubferenc-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: jakubferenc-composer
    volumes:
      - ./:/app
    working_dir: /app
    command: install

volumes:
  db_data:
