services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jakubferenc-wp
    volumes:
      - ./www:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: jakubferenc-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: jakubferenc-composer
    volumes:
      - ./:/app
    working_dir: /app
    command: install

  caddy:
    image: caddy:latest
    container_name: jakubferenc-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data:
  caddy_data:
  caddy_config:
